name: run rain_scraper.py

on:
  schedule:
    - cron: '0 11 * * *'  # every day at 11:00 (30 min after pollen scraper)
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      script: src/rain_scraper.py
      commit_message: 'rain scraper: updated data'
    secrets: inherit
