name: run main.py

on:
  schedule:
    - cron: '30 10 * * *'  # every day at 10:30
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      script: src/main.py
      commit_message: 'new scraper: updated data'
    secrets: inherit
