name: Test Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      script: src/main.py --dry-run
      commit_message: 'test scraper: updated test data'
      add_paths: data/test/
    secrets: inherit
